[package]
name = "editor"
version = "0.1.0"
authors = ["SmnTin <smn.pankv@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.9.1", default-features = true }
bevy_easings = "0.9.0"
game = { path = "../game" }
