name: Continuous deployment
on: [ push, pull_request ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v2

      - run: rustup toolchain install nightly --profile minimal

      - uses: jetli/trunk-action@v0.1.0

      - uses: jetli/wasm-bindgen-action@v0.1.0

      - uses: Swatinem/rust-cache@v2.2.0
        with:
          cache-on-failure: "true"
          key: ${{ runner.os }}-rust-cache-v3


      - run: trunk build --release --public-url forestry-game

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check