name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install linux-specific deps
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2.2.0
        with:
          cache-on-failure: "true"
          key: ${{ runner.os }}-rust-cache-all-v3

      - run: cargo build

  release:
    name: Build and deploy WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v2

      - uses: jetli/trunk-action@v0.1.0

      - uses: jetli/wasm-bindgen-action@v0.1.0

      - uses: Swatinem/rust-cache@v2.2.0
        with:
          cache-on-failure: "true"
          key: ${{ runner.os }}-rust-cache-v3


      - run: trunk build --release --public-url forestry-game

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check